// src/layout/fillerText.ts — filler sentences and word bank (data for T-020)
// Generator logic in T-022; this file is data only to respect 600-line limit.

export const FILLER_SENTENCES: string[] = [
  'Markets closed higher on steady volume.',
  'Analysts warned of volatility ahead.',
  'Officials met to discuss the proposal.',
  'The report cites a sharp increase in demand.',
  'Investors await the quarterly results.',
  'A new study highlights the trend.',
  'Traders reacted to the morning headlines.',
  'The committee approved the measure by a narrow margin.',
  'Economists forecast a modest recovery.',
  'Local leaders announced a joint initiative.',
  'The survey found broad public support.',
  'Shares fluctuated throughout the session.',
  'The agency released its annual review.',
  'Experts debated the policy in a forum.',
  'The forecast points to continued growth.',
  'Companies reported stronger than expected earnings.',
  'The mayor outlined a plan for the district.',
  'Researchers noted a pattern in the data.',
  'The edition went to press before midnight.',
  'Editors reviewed the final copy for errors.',
  'The front page carried the breaking story.',
  'Correspondents filed updates from the scene.',
  'The bulletin was printed on recycled paper.',
  'Readers queued for the morning edition.',
  'The headline drew attention on newsstands.',
  'Archives hold decades of printed history.',
  'The press run finished ahead of schedule.',
  'Circulation rose for the third week in a row.',
  'The column offered a different perspective.',
  'The article quoted several independent sources.',
  'The story continued on page four.',
  'Late wires added a final correction.',
];

export const FILLER_WORDS: string[] = [
  'market',
  'report',
  'analysis',
  'policy',
  'economy',
  'trade',
  'growth',
  'forecast',
  'record',
  'update',
  'brief',
  'press',
  'edition',
  'column',
  'source',
  'data',
  'survey',
  'trend',
  'volume',
  'session',
  'review',
  'measure',
  'plan',
  'study',
];

export const SAMPLE_PHRASES: string[] = [
  'Breaking news from the wire.',
  'Extra edition now on sale.',
  'Daily bulletin for subscribers.',
];
